#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0x015E339411694A6E (alex@caoua.org)
#
Name     : sndio
Version  : 1.9.0
Release  : 7
URL      : http://www.sndio.org/sndio-1.9.0.tar.gz
Source0  : http://www.sndio.org/sndio-1.9.0.tar.gz
Source1  : http://www.sndio.org/sndio-1.9.0.tar.gz.asc
Summary  : small audio and MIDI framework
Group    : Development/Tools
License  : ISC
Requires: sndio-bin = %{version}-%{release}
Requires: sndio-filemap = %{version}-%{release}
Requires: sndio-lib = %{version}-%{release}
Requires: sndio-man = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-configure
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package bin
Summary: bin components for the sndio package.
Group: Binaries
Requires: sndio-filemap = %{version}-%{release}

%description bin
bin components for the sndio package.


%package dev
Summary: dev components for the sndio package.
Group: Development
Requires: sndio-lib = %{version}-%{release}
Requires: sndio-bin = %{version}-%{release}
Provides: sndio-devel = %{version}-%{release}
Requires: sndio = %{version}-%{release}

%description dev
dev components for the sndio package.


%package filemap
Summary: filemap components for the sndio package.
Group: Default

%description filemap
filemap components for the sndio package.


%package lib
Summary: lib components for the sndio package.
Group: Libraries
Requires: sndio-filemap = %{version}-%{release}

%description lib
lib components for the sndio package.


%package man
Summary: man components for the sndio package.
Group: Default

%description man
man components for the sndio package.


%prep
%setup -q -n sndio-1.9.0
cd %{_builddir}/sndio-1.9.0
pushd ..
cp -a sndio-1.9.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1681403933
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%configure --disable-static || ./configure --prefix=/usr --without-libbsd --libdir=/usr/lib64
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static || ./configure --prefix=/usr --without-libbsd --libdir=/usr/lib64
make  %{?_smp_mflags}
popd
%install
export SOURCE_DATE_EPOCH=1681403933
rm -rf %{buildroot}
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/aucat
/usr/bin/midicat
/usr/bin/sndioctl
/usr/bin/sndiod
/usr/share/clear/optimized-elf/bin*

%files dev
%defattr(-,root,root,-)
/usr/include/sndio.h
/usr/lib64/glibc-hwcaps/x86-64-v3/libsndio.so
/usr/lib64/libsndio.so
/usr/lib64/pkgconfig/sndio.pc
/usr/share/man/man3/mio_close.3
/usr/share/man/man3/mio_eof.3
/usr/share/man/man3/mio_nfds.3
/usr/share/man/man3/mio_open.3
/usr/share/man/man3/mio_pollfd.3
/usr/share/man/man3/mio_read.3
/usr/share/man/man3/mio_revents.3
/usr/share/man/man3/mio_write.3
/usr/share/man/man3/sio_close.3
/usr/share/man/man3/sio_eof.3
/usr/share/man/man3/sio_getcap.3
/usr/share/man/man3/sio_getpar.3
/usr/share/man/man3/sio_initpar.3
/usr/share/man/man3/sio_nfds.3
/usr/share/man/man3/sio_onmove.3
/usr/share/man/man3/sio_onvol.3
/usr/share/man/man3/sio_open.3
/usr/share/man/man3/sio_pollfd.3
/usr/share/man/man3/sio_read.3
/usr/share/man/man3/sio_revents.3
/usr/share/man/man3/sio_setpar.3
/usr/share/man/man3/sio_setvol.3
/usr/share/man/man3/sio_start.3
/usr/share/man/man3/sio_stop.3
/usr/share/man/man3/sio_write.3
/usr/share/man/man3/sioctl_close.3
/usr/share/man/man3/sioctl_eof.3
/usr/share/man/man3/sioctl_nfds.3
/usr/share/man/man3/sioctl_ondesc.3
/usr/share/man/man3/sioctl_onval.3
/usr/share/man/man3/sioctl_open.3
/usr/share/man/man3/sioctl_pollfd.3
/usr/share/man/man3/sioctl_revents.3
/usr/share/man/man3/sioctl_setval.3

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-sndio

%files lib
%defattr(-,root,root,-)
/usr/lib64/glibc-hwcaps/x86-64-v3/libsndio.so.7
/usr/lib64/glibc-hwcaps/x86-64-v3/libsndio.so.7.0
/usr/lib64/glibc-hwcaps/x86-64-v3/libsndio.so.7.2
/usr/lib64/libsndio.so.7
/usr/lib64/libsndio.so.7.0
/usr/lib64/libsndio.so.7.2

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/aucat.1
/usr/share/man/man1/midicat.1
/usr/share/man/man1/sndioctl.1
/usr/share/man/man7/sndio.7
/usr/share/man/man8/sndiod.8
